### PR TITLE
Update the terraform-doc version to v0.10.1

### PR DESCRIPTION
**Pull request by clear-ryan**
# Description
Update the terraform-doc version to the latest version to be able to utilize config files

# Changes
- v0.9.1 => v0.10.1

### CODE REVIEW

**Comment by tomasbackman** [comment]
would be great! @Dirrk @mwarkentin

**Comment by ev1lm0nk3y** [comment]
I'm not sure why the docker test is failing, I cannot see details.

**Comment by clear-ryan** [comment]
@Dirrk just in case you don't get updates for this repo

**Comment by wagnst** [comment]
@Dirrk any update here? is this action dead?

**Comment by willscripted** [comment]
It looks like this project has life over in [terraform-docs/gh-actions](https://github.com/terraform-docs/gh-actions). There's even a help section on its use in the [terraform-docs website](https://terraform-docs.io/user-guide/how-to/#github-action)

As of writing, they are not on v0.13 yet. But a pr there may receive more attention.

cc #28 , #26

**Comment by ev1lm0nk3y** [comment]
Thanks for the pointer!

**Comment by clear-ryan** [comment]
Definitely thanks for the pointer

**Comment by Dirrk** [comment]
@clear-ryan thank you for your PR but I accidentally turned off notifications for this repository as the original developer for terraform-docs asked to move the repository over to that org.  I am deprecated this repository and will update the docs.  Please use https://github.com/terraform-docs/gh-actions

**Pull request closed without merging**
